### ISSUE TITLE
r6-api-caching not caching

### ISSUE THREAD

**Issue by BlackCatTB** [PoloLacoste/r6-api#10]
Heyho,
found that it's not caching to redist and or mongodb.

Tried it with 
`...
      - ENABLE_CACHING=1
...`
and 
`...
      - ENABLE_CACHING=true
...`
in docker-compose as arguments.
I kinda gave up tying to find why and you know ur code better than me :)

PS: also also you should probably add an `RUN npm update --depth 10` somewhere in ur dockerfile so the r6api.js gets updated properly.

thank you in advance xx
great project

**Comment by BlackCatTB** [comment]
Oh figured it out, you might wanna change `ENABLE_CACHING` to `CACHING` in ur readme. u got the env-getter set to just CACHING in /dist/services.modules.js hihi :)
![image](https://user-images.githubusercontent.com/31024398/174694929-1b3c5020-e3de-44f2-9827-af748507d3fa.png)

**Comment by PoloLacoste** [comment]
> Oh figured it out, you might wanna change `ENABLE_CACHING` to `CACHING` in ur readme. u got the env-getter set to just CACHING in /dist/services.modules.js hihi :) ![image](https://user-images.githubusercontent.com/31024398/174694929-1b3c5020-e3de-44f2-9827-af748507d3fa.png)

Oups.
Thank you for noticing!
